name: netzoon
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+11

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0
  equatable: ^2.0.5
  retrofit: ^4.0.1
  get_it: ^7.2.0
  flutter_svg: ^2.0.4
  internet_connection_checker: ^0.0.1+4
  form_field_validator: ^1.1.0
  dio: ^5.1.1
  injectable: ^2.1.1
  shared_preferences: ^2.1.0
  json_annotation: ^4.8.0
  shimmer: ^2.0.0
  auto_route: ^6.1.0
  easy_localization: ^3.0.1
  carousel_slider: ^4.2.1
  google_nav_bar: ^5.0.6
  flutter_localizations: 
    sdk: flutter  
  dropdown_button2: ^2.0.0
  cached_network_image: ^3.2.3
  dynamic_height_grid_view: ^0.0.3
  geolocator: ^10.1.0
  country_code_picker: ^3.0.0
  youtube_player_flutter: ^8.1.2
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+4
  flutter_icons_null_safety: ^1.1.0
  http: ^0.13.6
  http_parser: ^4.0.2
  intl: ^0.18.0
  # date_time_picker: ^2.1.0
  font_awesome_flutter: ^10.4.0
  sms_autofill: ^2.3.0
  rxdart: ^0.27.7
  localization: ^2.1.0
  share_plus: ^7.0.2
  path_provider: ^2.0.15
  custom_clippers: ^2.0.0
  video_player: ^2.6.1
  chewie: ^1.7.0
  animated_splash_screen: ^1.3.0
  flutter_typeahead: ^4.6.1
  file_picker: ^5.3.1
  open_file: ^3.3.2
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^14.1.1
  lottie: ^2.3.2
  geocoding: ^2.1.1
  flutter_rating_bar: ^4.0.1
  sn_progress_dialog: ^1.1.3
  sendbird_chat_sdk: ^4.0.4
  dash_chat_2: ^0.0.15
  flutter_stripe: ^9.4.0
  dartz: ^0.10.1
  flutter_dotenv: ^5.1.0
  readmore: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3
  built_value_generator: ^8.4.4
  json_serializable: ^6.6.1
  retrofit_generator: ^7.0.8 
  auto_route_generator: ^6.1.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/netzoon_appicon.jpg"
  min_sdk_android: 21  
  


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/ar.json
    - assets/translations/en.json
    - assets/
    - .env

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

   